name: Init Gradle Wrapper

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Init Gradle Wrapper
        run: |
          gradle wrapper
      - name: Upload wrapper files
        uses: actions/upload-artifact@v4
        with:
          name: gradle-wrapper
          path: |
            gradlew
            gradlew.bat
            gradle/wrapper
