name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission
        run: chmod +x ./gradlew

      - name: Build and check
        run: |
          ./gradlew assembleDebug
          ./gradlew check

      - name: Find APK
        id: find-apk
        run: |
          APK_PATH=$(find app/build/outputs/apk -name '*.apk' | head -1)
          echo "APK_PATH=${APK_PATH}" >> $GITHUB_OUTPUT
          echo "Found APK: ${APK_PATH}"

      - name: Upload APK
        if: steps.find-apk.outputs.APK_PATH != ''
        uses: actions/upload-artifact@v4
        with:
          name: whispnote-apk
          path: ${{ steps.find-apk.outputs.APK_PATH }}
