name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      # 3. Gradle caching
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            build
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 4. Make gradlew executable
      - name: Grant execute permission
        run: chmod +x ./gradlew

      # 5. Build verification
      - name: Run gradle checks
        run: ./gradlew check

      # 6. Build APK
      - name: Build debug APK
        run: ./gradlew assembleDebug

      # 7. Upload artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: whispnote-apk
          path: app/build/outputs/apk/debug/app-debug.apk
